-- Drop existing schema and recreate
DROP DATABASE IF EXISTS ELECTRONICA_DW;
CREATE DATABASE ELECTRONICA_DW;
USE ELECTRONICA_DW;

-- Drop tables if exist (order matters due to FK constraints)
DROP TABLE IF EXISTS FACTS;
DROP TABLE IF EXISTS STORES;
DROP TABLE IF EXISTS SUPPLIERS;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS DATES;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS ORDERS;

-- Create dimension tables
CREATE TABLE PRODUCTS (
  ProductID VARCHAR(8) NOT NULL,
  productName VARCHAR(35) NOT NULL,
  productPrice DECIMAL(10,2) DEFAULT 0.0 NOT NULL,
  PRIMARY KEY (ProductID)
);

CREATE TABLE CUSTOMERS (
  CustomerID VARCHAR(5) NOT NULL,
  CustomerName VARCHAR(40) NOT NULL,
  Gender VARCHAR(15) NOT NULL,
  PRIMARY KEY (CustomerID)
);

CREATE TABLE STORES (
  storeID VARCHAR(5) NOT NULL,
  storeName VARCHAR(25) NOT NULL,
  PRIMARY KEY (storeID)
);

CREATE TABLE ORDERS (
  OrderID VARCHAR(10) NOT NULL,
  OrderDate VARCHAR(25) NOT NULL,
  QuantityOrdered VARCHAR(10) NOT NULL,
  PRIMARY KEY (OrderID)
);

CREATE TABLE SUPPLIERS (
  supplierID VARCHAR(6) NOT NULL,
  supplierName VARCHAR(35) NOT NULL,
  PRIMARY KEY (supplierID)
);

CREATE TABLE DATES (
  DATE_ID VARCHAR(30) NOT NULL,
  PRIMARY KEY (DATE_ID)
);

-- Create fact table with foreign keys
CREATE TABLE FACTS (
  DATE_ID VARCHAR(30) NOT NULL,
  ProductID VARCHAR(8) NOT NULL,
  storeID VARCHAR(5),
  supplierID VARCHAR(6),
  CustomerID VARCHAR(5),
  OrderID VARCHAR(10),
  SALE DECIMAL(10,2) DEFAULT 0.0 NOT NULL,
  PRIMARY KEY (OrderID, ProductID, storeID, supplierID, CustomerID, DATE_ID),
  FOREIGN KEY (storeID) REFERENCES STORES(storeID),
  FOREIGN KEY (ProductID) REFERENCES PRODUCTS(ProductID),
  FOREIGN KEY (DATE_ID) REFERENCES DATES(DATE_ID),
  FOREIGN KEY (supplierID) REFERENCES SUPPLIERS(supplierID),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMERS(CustomerID),
  FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);

COMMIT;