use electronica_dw;


DROP TABLE if exists facts;

DROP TABLE if exists stores;
DROP TABLE if exists suppliers;
DROP TABLE if exists customers;

DROP TABLE if exists dates;
DROP TABLE if exists products;
DROP TABLE if exists orders;





  CREATE TABLE `PRODUCTS` (
  `ProductID` VARCHAR(8) NOT NULL, 
  `productName` VARCHAR(35) NOT NULL, 
  `productPrice` DECIMAL(5,2) DEFAULT (0.0) NOT NULL,
   CONSTRAINT ProductID PRIMARY KEY (ProductID));

CREATE TABLE `CUSTOMERS` (
  `CustomerID` VARCHAR(5) NOT NULL, 
  `CustomerName` VARCHAR(40) NOT NULL, 
  `Gender` VARCHAR(15) NOT NULL,
  CONSTRAINT CustomerID PRIMARY KEY (CustomerID));

CREATE TABLE `STORES` (
  `storeID` VARCHAR(5) NOT NULL, 
  `storeName` VARCHAR(25) NOT NULL,
  
  CONSTRAINT storeID PRIMARY KEY ( storeID));

CREATE TABLE `ORDERS` (
  `OrderID` VARCHAR(5) NOT NULL, 
  `OrderDate` VARCHAR(25) NOT NULL,
  `QuantityOrdered` VARCHAR(10) NOT NULL,
  CONSTRAINT OrderID PRIMARY KEY ( OrderID));


CREATE TABLE `SUPPLIERS` (
  `supplierID` VARCHAR(6) NOT NULL, 
  `supplierName` VARCHAR(35) NOT NULL,  
  CONSTRAINT supplierID PRIMARY KEY ( supplierID));


CREATE TABLE `DATES` (
`DATE_ID` VARCHAR(30) NOT NULL,
CONSTRAINT DATE_ID PRIMARY KEY ( DATE_ID));

CREATE TABLE `FACTS` (
`DATE_ID` VARCHAR(30) NOT NULL,
`ProductID` VARCHAR(8) NOT NULL, 
`storeID` VARCHAR(5) NOT NULL,
`supplierID` VARCHAR(6) NOT NULL, 
`CustomerID` VARCHAR(6) NOT NULL,
`OrderID` VARCHAR(10) NOT NULL, 
`SALE` DECIMAL(5,2) DEFAULT (0.0) NOT NULL,
   
CONSTRAINT FACTS_PK PRIMARY KEY (OrderID,ProductID,storeID,supplierID,CustomerID,DATE_ID),

FOREIGN KEY ( storeID) REFERENCES STORES( storeID),
FOREIGN KEY ( ProductID) REFERENCES PRODUCTS( ProductID),
FOREIGN KEY ( DATE_ID) REFERENCES DATES( DATE_ID),
FOREIGN KEY ( DATE_ID) REFERENCES DATES( DATE_ID),
FOREIGN KEY ( supplierID) REFERENCES SUPPLIERS( supplierID),
FOREIGN KEY ( CustomerID) REFERENCES CUSTOMERS( CustomerID),
FOREIGN KEY ( OrderID) REFERENCES ORDERS( OrderID)
);
  COMMIT;